# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.F_CrossSection <- function(position) {
    .Call('_tsExtra_F_CrossSection', PACKAGE = 'tsExtra', position)
}

.F_Yearly <- function(year) {
    .Call('_tsExtra_F_Yearly', PACKAGE = 'tsExtra', year)
}

.F_Quarterly <- function(year, quarter) {
    .Call('_tsExtra_F_Quarterly', PACKAGE = 'tsExtra', year, quarter)
}

.F_Monthly <- function(year, month) {
    .Call('_tsExtra_F_Monthly', PACKAGE = 'tsExtra', year, month)
}

.F_MultiYearly <- function(year, z) {
    .Call('_tsExtra_F_MultiYearly', PACKAGE = 'tsExtra', year, z)
}

.F_XTimesAYear <- function(year, x, position) {
    .Call('_tsExtra_F_XTimesAYear', PACKAGE = 'tsExtra', year, x, position)
}

.F_XTimesZYears <- function(year, x, z, position) {
    .Call('_tsExtra_F_XTimesZYears', PACKAGE = 'tsExtra', year, x, z, position)
}

.F_Weekly <- function(year, month, day) {
    .Call('_tsExtra_F_Weekly', PACKAGE = 'tsExtra', year, month, day)
}

.F_MultiWeekly <- function(year, month, day, k) {
    .Call('_tsExtra_F_MultiWeekly', PACKAGE = 'tsExtra', year, month, day, k)
}

.F_Daily <- function(year, month, day) {
    .Call('_tsExtra_F_Daily', PACKAGE = 'tsExtra', year, month, day)
}

.F_MultiDaily <- function(year, month, day, k) {
    .Call('_tsExtra_F_MultiDaily', PACKAGE = 'tsExtra', year, month, day, k)
}

.F_DailyInWeek <- function(year, month, day, weekStart, weekEnd, forward) {
    .Call('_tsExtra_F_DailyInWeek', PACKAGE = 'tsExtra', year, month, day, weekStart, weekEnd, forward)
}

.F_ListString <- function(items, value) {
    .Call('_tsExtra_F_ListString', PACKAGE = 'tsExtra', items, value)
}

.F_ListDate <- function(items, value) {
    .Call('_tsExtra_F_ListDate', PACKAGE = 'tsExtra', items, value)
}

.F_Hourly <- function(day, hour) {
    .Call('_tsExtra_F_Hourly', PACKAGE = 'tsExtra', day, hour)
}

.F_Minutely <- function(day, minute) {
    .Call('_tsExtra_F_Minutely', PACKAGE = 'tsExtra', day, minute)
}

.F_Secondly <- function(day, second) {
    .Call('_tsExtra_F_Secondly', PACKAGE = 'tsExtra', day, second)
}

.F_XTimesADay <- function(day, x, position) {
    .Call('_tsExtra_F_XTimesADay', PACKAGE = 'tsExtra', day, x, position)
}

.ToString_F <- function(value) {
    .Call('_tsExtra_ToString_F', PACKAGE = 'tsExtra', value)
}

.ToClassString_F <- function(value) {
    .Call('_tsExtra_ToClassString_F', PACKAGE = 'tsExtra', value)
}

.ToString_F0 <- function(value) {
    .Call('_tsExtra_ToString_F0', PACKAGE = 'tsExtra', value)
}

.Parse_F <- function(str, classStr) {
    .Call('_tsExtra_Parse_F', PACKAGE = 'tsExtra', str, classStr)
}

.Sequence_F0 <- function(start, length, by) {
    .Call('_tsExtra_Sequence_F0', PACKAGE = 'tsExtra', start, length, by)
}

.Sequence_F <- function(from, to, by) {
    .Call('_tsExtra_Sequence_F', PACKAGE = 'tsExtra', from, to, by)
}

.Variable <- function(data, name, startFrequency, fields) {
    .Call('_tsExtra_Variable', PACKAGE = 'tsExtra', data, name, startFrequency, fields)
}

.VariableToString <- function(w) {
    .Call('_tsExtra_VariableToString', PACKAGE = 'tsExtra', w)
}

.BindVariables <- function(varList, interpolate, adjustLeadLags, numExo, horizon) {
    .Call('_tsExtra_BindVariables', PACKAGE = 'tsExtra', varList, interpolate, adjustLeadLags, numExo, horizon)
}

